// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG80wx_CRWA992wIQXOqtjfrpPkcNAaEY',
    appId: '1:318368576926:web:ef8de32761b100d949528f',
    messagingSenderId: '318368576926',
    projectId: 'flutterchatapp-6c17f',
    authDomain: 'flutterchatapp-6c17f.firebaseapp.com',
    storageBucket: 'flutterchatapp-6c17f.firebasestorage.app',
    measurementId: 'G-3GZ99HEB8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAiPC70Qi_lcLw-R05WvLphyUcd5dzFRw',
    appId: '1:318368576926:android:2532f3d11550713e49528f',
    messagingSenderId: '318368576926',
    projectId: 'flutterchatapp-6c17f',
    storageBucket: 'flutterchatapp-6c17f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC56r4-yPJpCwlIRXY5r08V-7J4EPCYIxA',
    appId: '1:318368576926:ios:0ffd6eafa5c4fc8449528f',
    messagingSenderId: '318368576926',
    projectId: 'flutterchatapp-6c17f',
    storageBucket: 'flutterchatapp-6c17f.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC56r4-yPJpCwlIRXY5r08V-7J4EPCYIxA',
    appId: '1:318368576926:ios:0ffd6eafa5c4fc8449528f',
    messagingSenderId: '318368576926',
    projectId: 'flutterchatapp-6c17f',
    storageBucket: 'flutterchatapp-6c17f.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG80wx_CRWA992wIQXOqtjfrpPkcNAaEY',
    appId: '1:318368576926:web:0d3ab2158501878549528f',
    messagingSenderId: '318368576926',
    projectId: 'flutterchatapp-6c17f',
    authDomain: 'flutterchatapp-6c17f.firebaseapp.com',
    storageBucket: 'flutterchatapp-6c17f.firebasestorage.app',
    measurementId: 'G-R9NHFJ1JV3',
  );
}
